# Generated by Django 4.0.2 on 2022-02-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessagePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=64, unique=True, verbose_name='Message role')),
                ('text', models.TextField(verbose_name='Message text')),
            ],
            options={
                'verbose_name': 'Message Pattern',
                'verbose_name_plural': 'Message Patterns',
            },
        ),
    ]
