# Generated by Django 4.0.2 on 2022-02-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, default=None, max_length=32, verbose_name='Telegram username')),
                ('first_name', models.CharField(max_length=64, verbose_name='Telegram first_name')),
                ('is_subscribe', models.BooleanField(default=False, verbose_name='Is subscribe')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
            ],
            options={
                'verbose_name': 'Telegram User',
                'verbose_name_plural': 'Telegram Users',
            },
        ),
    ]
